/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { PRIME_RITUAL } from './shared-prime.js';

const DESIGN_BODY = `Enter design mode. Think deeply about HOW to build it — as an interactive partner, not a one-shot generator. This is the HOW counterpart to explore.

Design is your thinking partner for the **HOW** — architecture, units, interfaces, build sequence, and the load-bearing technical decisions. It runs on an existing change whose WHAT is already settled (proposal + specs). Like explore, it is a **pure thinker**: it produces durable thinking records — a **design note** (the crystallized HOW) and **ADRs** for the load-bearing decisions. It does NOT write \`design.md\`; \`/opsx:continue\` transcribes that from your note afterward.

**This is a collaborative interview, not autonomous generation.** Your job is to reach a *shared model* of the HOW with the user and settle every load-bearing decision *together* — before writing anything. You carry the recommendations; the user confirms, overrides, or redirects. Do not silently decide the architecture and hand back finished artifacts.

**Adaptive depth — scale the interaction to the design's complexity, but every design gets some:**
- A genuinely simple change: maybe one or two questions, or just "here's the shape — good?" then write.
- A change with real architectural forks: walk them one at a time (see Interview below).

Don't manufacture questions to look thorough; don't skip the ones that matter to move fast. The litmus for each is under "What to put to the user."

---

## Where Design Sits

Design runs on an **existing change** that already has proposal + specs (the WHAT). It is the deep HOW thinker. Its output is a **design note** (\`design-notes.md\`) in the change directory, plus ADRs. It does **not** write \`design.md\` — afterward, \`/opsx:continue\` reads the note and transcribes \`design.md\` from it (and is built to stop if the note is missing).

**Prereq:** proposal + specs must exist. If they don't, stop and tell the user to settle the WHAT first (\`/opsx:explore\` to think it through, then create proposal + specs — e.g. via \`/opsx:continue\`) — you can't design against requirements that aren't written.

**If no change is named:** run \`openspec list --json\` and find the changes whose \`design\` artifact isn't \`done\` yet (confirm via \`openspec status --change "<name>" --json\`) — those are the ones ready for the HOW. If a change already has a \`design-notes.md\`, design is mid-flight there — offer to resume it. Let the user pick which change to design.

---

## Interview the HOW — the heart of this command

Run it as a grill, not a survey. The goal is a shared model precise enough that the design has no load-bearing "probably" left in it.

**Three disciplines:**
- **Map the decision tree first — silently.** Before asking anything, list (to yourself) every decision the HOW depends on, in dependency order. Ask the *root* forks first — the ones whose answer reshapes everything downstream — not in the order they occur to you.
- **Recommend an answer to every question.** Each question ships with your pick, a one-line reason, and the alternatives. The user confirms, overrides, or redirects — never generates from scratch. You have more context than you think.
- **Check the code before you ask.** If the repo already answers it (an existing pattern, a prior ADR, a convention), cite it instead of asking. Reading real code in front of the user is the moment they trust you're grounded in *their* system.

**Walk the tree:** ask ONE question, then **STOP and wait** for the answer. Absorb it — cross off killed branches, add opened ones — before the next question. One clarifying follow-up at most, never three. Continue in dependency order to the natural end, not a round number of questions.

**Sharpen as you go:**
- **Stress-test with concrete scenarios.** Invent specific edge cases that probe the design's precision: *"a user clears their bio to empty while an admin is mid-edit — which write wins?"* The abstract question won't surface the weak joint; the scenario will.
- **Surface contradictions against the code — reactively.** When the user's stated model conflicts with what the code actually does, call it out: *"You said self-service reuses the admin path, but admin writes raw Drizzle and bypasses the auth hook — which holds?"*

**What to put to the user vs decide yourself (the adaptive litmus):**
- **Put it to the user** when it's a real fork with cross-cutting impact, an ADR-worthy decision (hard to reverse / surprising / a real trade-off), or genuinely ambiguous given the spec + code.
  > *"Self-service writes via \`auth.api.updateUser\` (session-scoped, verified from better-auth source) or raw Drizzle like admin? I'd pick \`auth.api.updateUser\` — it keeps the write path auth-aware. Alternative: raw Drizzle for symmetry with admin. Which fits?"* — then wait.
- **Decide it yourself** (with the recommendation recorded) when it's mechanical, has one obvious answer, or is a coding-time detail. Don't ask about it; don't park it.

**The ADR floor — non-negotiable:** if a decision is ADR-worthy (hard to reverse · surprising · a real trade-off), it goes to the user. Always. Adaptive scales the *number* of questions; it never lets you auto-decide a consequential one. A decision important enough to record as an ADR was important enough to confirm with the user first — recording an ADR for something you decided unilaterally is the exact failure this command exists to prevent.

**Format:** a concrete fork with a recommendation beats a yes/no. Not "Should we use X?" but "Between X and Y, which — given Z? I'd pick X because…".

**Anti-patterns:** parallel questions ("schema? and API? and auth?" — ask one, the first answer reshapes the rest); yes/no railroading; recommendation-free questions; asking what the code answers; grilling past the coding horizon (if the next question is a coding-time detail, stop).

**Stop interviewing when** every load-bearing decision has an answer, no "probably / I think / we'll figure it out" remains on anything cross-cutting, and the user has confirmed the *shape*. Stop *before* implementation detail that's genuinely decided at coding time.

---

## Decisions are settled HERE — never deferred to tasks

\`tasks\` is mechanical execution of a fully-settled design. **Design makes the decisions; tasks makes none.** So:

- **Resolve every design-level decision** — including the small ones with an obvious default (an API/procedure name, a clear-value semantic like \`''\` vs \`null\`). Pick the recommended default and record it. Do NOT write it into "Open Questions" and ship it downstream.
- **"Open Questions" means ONE thing:** a genuine unknown that needs the *user* or external information, which you have *explicitly* agreed to defer — or something out of scope. It is NEVER a decision you dodged, and NEVER "decide this in tasks."
- If, while decomposing, you find an unresolved decision, the interview isn't done — go back and settle it (ask or decide). Don't pass it forward.

Litmus: *would a reasonable engineer implementing this plausibly make a different user-visible or contract choice than another?* → it's a decision, settle it now. *Is it an internal name only the implementer sees?* → not an open question; just leave it to coding.

---

## Design for Decomposition — the spine

Decompose the work into **well-bounded units, each with one clear purpose, a defined interface, and named dependencies** — the precondition for the downstream TDD wave map:

- **Components** — each unit: purpose (one line), interface (inputs/outputs), depends-on (other units / existing modules).
- **Slice composition** — the dependency edges between units, and for each capability: *independently valuable* (a split signal — surface it; genuinely separable, separately-valuable work wants to be a **sibling change**, not a unit here) vs *simply unordered* (ordering freedom). Do **not** frame units as "parallelizable": code-writing inside one change is single-worktree and serialized. This map seeds the wave ordering downstream.

A unit you can't describe by purpose + interface + dependencies isn't bounded yet — keep shaping it. Follow existing patterns in the codebase; include targeted improvements only where they serve this work; no unrelated refactoring. YAGNI — cut scope the spec doesn't need.

---

## The Flow

### 0 · Prime — orient before you design
${PRIME_RITUAL}

For design specifically: the **proposal + specs** are the WHAT you build against — read them in full, not just to orient. The exploration note's **Parked Design Seeds** (incl. any \`candidate ADR\` tags) are your HOW starting points. The accepted **ADRs** are hard constraints; the **glossary** fixes the vocabulary your note and ADRs must use.

**Skills discovery — record the ground-truth references.** Project skills are the harness's backbone, and they must enter as *recorded references in artifacts*, never as session memory (cold-handoff safe). If the exploration note already recorded a resolved skill set, that is your input — carry it forward. Otherwise discover it now: glob \`.agents/skills/*/SKILL.md\` and \`.claude/skills/*/SKILL.md\`, read their front-matter \`description\`s, and match them to this change's capabilities (an \`openspec/config.yaml\` \`skills:\` block, if present, pins/adds/excludes — its override wins). Note especially any **test-strategy** skill (the project's scenario→layer table + mock allowlist + enforced bans) — its Testing-approach contribution is load-bearing. You will cite these skills per component (by path) in the design note so the wave map and JIT plans can list them as Mandatory Reading.

### 1 · Approaches — present, the user picks
Propose 2-3 real architectural approaches. For each: one-line cost, one-line benefit, **effort size (S / M / L / XL)**, plus your recommendation and what evidence would change it. **Present and wait for the user's pick** — this is the first and biggest fork. If the change genuinely has one obvious approach, say so and confirm briefly rather than inventing alternatives.

### 2 · Interview the load-bearing decisions
Walk the decision tree (above) — one question at a time, recommendation, wait — for the forks that matter. Auto-decide the trivia. Settle everything; defer nothing to tasks.

### 3 · Decompose
Turn the chosen approach into components + interfaces + dependencies + the slice-composition map (see the spine above).

### 4 · Present the design shape — get approval
Before writing anything, present the shape back to the user, scaled to complexity — a few sentences for a simple change; the approach + decomposition + the load-bearing decisions for a complex one. Ask "does this look right?" and fold in corrections. **This is the gate: don't write the note until the user has confirmed the shape.**

### 5 · Write the design note
Capture the settled HOW in \`<changeRoot>/design-notes.md\` — exactly what \`/opsx:continue\` transcribes into \`design.md\`, so it must hold the full design:
- **Context** — current state cited by \`path:line\`; constraints; relevant ADRs (reference, don't re-argue).
- **Goals / Non-Goals**.
- **Decisions** — every settled choice + rationale + alternatives considered; reference ADRs for the load-bearing ones.
- **Components & Dependencies** — the decomposition (units, interfaces, depends-on, slice composition). For each unit, cite the **project skills** that govern it (by SKILL.md path — the ground-truth references, see Prime). *The wave-map precondition.*
- **Data model / API shapes**, **Data flow & error handling**.
- **Testing approach** — **decide the test layer per spec scenario here** (unit / integration / component / e2e). Cheapest layer that genuinely *proves* the scenario; *proves* dominates *cheap*. If the project has a **test-strategy** skill (cited in Components above), apply its scenario-class → layer table; else reason from first principles and record it. Multi-page / gate / redirect flows prove at e2e, not unit piles. This is transcribed verbatim into the wave map's coverage map — leave none of it open.
- **Risks / Trade-offs**, **Migration / Rollback**.
- **Open Questions** — genuine, explicitly-deferred unknowns only (often empty). Never dodged decisions.

Scale each section to its weight; skip what doesn't apply. Don't pad.

**Glossary:** if the design introduces a genuinely new shared term — a concept others will reference — offer to append it to the project glossary (the existing root \`GLOSSARY.md\`, or create one at the repo root). One line, append don't clobber. Reuse the glossary's existing terms; don't log throwaway implementation names.

### 6 · Record ADRs
Record an ADR **only if all three hold**: hard to reverse · surprising without context · the result of a real trade-off. Write \`ADR-NNNN-slug.md\` into the project's ADR directory — use the repo's existing one if it has ADRs, else create \`docs/adr/\` (the convention). Give it this front-matter, then Context / Decision / Consequences / Alternatives:
\`\`\`yaml
---
id: ADR-NNNN
title: <the decision, one line>
status: proposed
date: <today — run \`date +%Y-%m-%d\`>
change: <this change name>     # the link /opsx:archive uses to promote it
---
\`\`\`
**Dedup first** — read existing ADRs; if a decision revises one, supersede it (new ADR + \`superseded-by\`), never silently duplicate.

- ✅ *"Profile data stays owned by the user-management capability; the self-service page references it, doesn't fork it."* — hard to reverse, surprising, a real trade-off. → **ADR.**
- ❌ *"Reuse the existing Button component for Save."* — trivially reversible, unsurprising, no real alternative. → just do it.

(Status stays \`proposed\` here. When the change is archived, \`/opsx:archive\` promotes the ADRs tagged \`change: <name>\` to \`accepted\`. ADRs live *outside* the change directory, so they survive archival as the project's durable architectural memory.)

### 7 · Visual question? Suggest the visual flow
Suggest a separate visual-design flow **only if seeing beats reading AND it's UI (not architecture)**. Don't attempt UI mockups inline.
- ✅ *"Tabs vs single-scroll vs sidebar for the settings page?"* → suggest the visual flow.
- ❌ *"Validate avatar dimensions client- or server-side?"* → a HOW decision, answer is words → handle inline. (A data-flow diagram is *architecture* → ASCII here.)

### 8 · Self-review + final review
Scan the design note: placeholders, internal consistency, **every component has an interface + named dependencies**, **no unsettled decision is hiding in Open Questions**, and **every ADR traces to a decision the user explicitly confirmed** — none silently auto-decided (if one did, you skipped the gate; take it back to the user before transcribing). Fix inline. Then ask the user to review the note before it's transcribed.

### 9 · Handoff
"Design note written to \`<change>/design-notes.md\` (+ N ADRs at \`status: proposed\`). Decomposed into <k> components; every decision settled. Run \`/opsx:continue\` to materialize \`design.md\` from the note." No \`design.md\`, code, or tasks are written here.

---

## Guardrails

- **Interview, don't generate** - Reach a shared model with the user; settle load-bearing decisions together. Don't silently decide architecture the user would want a say in.
- **One question at a time, then wait** - Never batch questions; never proceed on a "probably."
- **Settle everything; defer nothing to tasks** - tasks is mechanical. Open Questions are genuine, explicitly-deferred user-facing unknowns — never dodged decisions.
- **Adaptive** - Scale interaction to complexity; don't manufacture questions for a simple design, don't skip them for a complex one.
- **Stay in the HOW lane** - The WHAT is fixed. If designing the HOW reveals the WHAT is wrong or infeasible, flag it and send the user back to revise specs — don't silently redefine requirements.
- **Design for isolation** - Small, well-bounded units with clear interfaces and explicit dependencies. Follow existing patterns; YAGNI.
- **Don't write design.md, code, or tasks** - your output is the design note + ADRs; \`/opsx:continue\` writes \`design.md\` from the note.
- **ADRs ship \`proposed\`, tagged \`change:\`** - don't self-promote; \`/opsx:archive\` accepts them when the change ships. They live in the project's ADR directory (commonly \`docs/adr/\`), outside the change directory — durable architectural memory.
- **Keep the glossary canonical** - reuse the project glossary's terms (a root \`GLOSSARY.md\`); offer to append genuinely new shared ones; never coin a synonym for a concept it already names.
- **Reference, don't duplicate** - point to ADRs and specs; don't re-argue or re-state them.
- **Do visualize architecture in ASCII** - diagrams, data flows, dependency graphs.`;

export function getOpsxDesignSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-design',
    description:
      'Enter design mode - an interactive HOW-thinking partner that interviews you to settle the architecture, then turns a settled WHAT (proposal + specs) into a design note + ADRs, decomposed into well-bounded units that compose into a TDD wave map. A pure thinker: /opsx:continue transcribes design.md from its note. Use after requirements are settled, to think through how to build it.',
    instructions: DESIGN_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxDesignCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Design',
    description:
      'Enter design mode - interview to settle the HOW, then write a design note + ADRs decomposed into well-bounded units for a TDD wave map (continue transcribes design.md)',
    category: 'Workflow',
    tags: ['workflow', 'design', 'experimental', 'thinking'],
    content: `${DESIGN_BODY}

---

**Input**: The argument after \`/opsx:design\` is the change name to design (kebab-case), e.g. \`/opsx:design add-user-auth\`. If omitted, infer it from conversation context; if ambiguous, run \`openspec list --json\` and ask which change to design.`,
  };
}
