/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const DESIGN_BODY = `Enter design mode. Think deeply about HOW to build it. This is the HOW counterpart to explore.

Design is your thinking partner for the **HOW** — the architecture, the units, the interfaces, the build sequence. It runs on an existing change whose WHAT is already settled (proposal + specs), and it produces \`design.md\` (the technical design) plus ADRs for the load-bearing architectural decisions.

**IMPORTANT: Design mode is for designing, not implementing.** You investigate the codebase as implementation substrate, decide the shape, and write \`design.md\` + ADRs. You do NOT write application code, and you do NOT write tasks — task breakdown and implementation are downstream (a task builder / your harness consumes this design).

**This is a stance with a spine.** Like explore, follow the thinking where it goes — but design has a concrete deliverable: a \`design.md\` decomposed cleanly enough that the work can be split into independent, parallelizable units.

---

## Where Design Sits

Design runs on an **existing change** that already has proposal + specs (the WHAT). It is the deep, opt-in HOW driver: it **creates — or replaces — \`design.md\`** for that change. If a mechanical \`design.md\` already exists (e.g. from an all-in-one generation), design replaces it with the considered one.

**Prereq:** proposal + specs must exist. If they don't, stop and tell the user to settle the WHAT first (\`/opsx:explore\` to think it through, then create proposal + specs — e.g. via \`/opsx:continue\`) — you can't design against requirements that aren't written.

---

## Design for Decomposition — the spine

The heart of this command, and the precondition for everything downstream: **decompose the work into well-bounded units, each with one clear purpose, a defined interface, and named dependencies.** That decomposition is what later lets the work be split across parallel agents — so make it explicit, not implied:

- **Components** — each unit: purpose (one line), interface (inputs/outputs), depends-on (other units / existing modules).
- **Build sequence & parallelism** — which units are independent (buildable in parallel) vs ordered (must follow a dependency). This is the seed of the task graph.

A unit you can't describe by purpose + interface + dependencies isn't bounded yet — keep shaping it. Smaller, well-bounded units are both better design and the thing that makes parallel task-building possible.

---

## The Flow

### 0 · Prime (read)
- \`openspec status --change "<name>" --json\` → resolve \`changeRoot\`, \`artifactPaths\`, \`actionContext\`.
- Read **proposal + specs** — the WHAT you're designing against.
- Read the exploration note's **Parked Design Seeds** (incl. any \`candidate ADR\` tags) if present.
- Read existing **ADRs** (\`openspec/adr/\`, or a project's \`docs/adr/\` if it uses one) and the **glossary** → the architectural constraints and canonical terms already in play.
- Orient: which capabilities are affected, what constraints bind, what's already decided.

### 1 · Grill the HOW
Critical interview in the HOW lane:
- Read code as **implementation substrate** — modules, patterns, integration points, what's genuinely reusable.
- **Carry a recommendation** on each question; **root before leaves**; **check the code before asking**.
- Attack feasibility: what's the riskiest assumption? what breaks at scale, or when a dependency fails?

### 2 · Approaches
Propose 2-3 real architectural approaches. For each: one-line cost, one-line benefit, and an **effort size (S / M / L / XL)**. Lead with your recommendation and say what evidence would change it. (Effort sizing belongs here — it's a HOW estimate.)

### 3 · Decompose (see "Design for Decomposition" above)
Turn the chosen approach into components + interfaces + dependencies + a parallelism map. This is the part the task builder depends on; don't skip or hand-wave it.

### 4 · Write design.md
Fill the change's \`design.md\` via \`openspec instructions design --change "<name>" --json\` (follow its template/rules) — but **deeply**, not mechanically:
- **Context** — current state cited by \`path:line\`; constraints; relevant ADRs (reference them, don't re-argue).
- **Goals / Non-Goals**.
- **Decisions** — key technical choices + rationale + alternatives considered; reference ADRs for the load-bearing ones.
- **Components & Dependencies** — the decomposition from step 3 (units, interfaces, depends-on, parallelism). *This is the task-builder precondition.*
- **Data model / API shapes** — concrete enough that an implementer makes no design decisions.
- **Data flow & error handling** — the happy path, and what happens when each step fails.
- **Testing approach** — what to cover (unit / integration / e2e), tied to the spec scenarios.
- **Risks / Trade-offs**, **Migration / Rollback**, **Open Questions**.

Scale each section to its weight; skip what doesn't apply. Don't pad to look thorough.

### 5 · Record ADRs
Record an ADR **only if all three hold**: hard to reverse · surprising without context · the result of a real trade-off. Write \`openspec/adr/ADR-NNNN-slug.md\` at \`status: proposed\`. **Dedup first** — read existing ADRs; if a decision revises one, supersede it (new ADR + \`superseded-by\` on the old), never silently duplicate. Respect an existing \`docs/adr/\` if the project uses one.

- ✅ *"Profile data stays owned by the user-management capability; the self-service page references it, doesn't fork it."* — reversing means reconciling two sources of truth (hard); a reader wonders why self-service has no profile model of its own (surprising); single-source vs independent evolution (real trade-off). → **ADR.**
- ❌ *"Reuse the existing Button component for Save."* — trivially reversible, unsurprising, no real alternative. → just do it; not an ADR.

(Status stays \`proposed\`; promotion to \`accepted\` is manual for now.)

### 6 · Visual question? Suggest the visual flow
Suggest a separate visual-design flow **only if seeing beats reading AND it's UI (not architecture)**. Don't attempt UI mockups inline.
- ✅ *"Tabs vs single-scroll vs sidebar for the settings page?"* → UI, a visual preference → suggest the visual flow.
- ❌ *"Validate avatar dimensions client- or server-side?"* → a HOW decision, the answer is words → handle inline. (A data-flow **diagram** is visual but it's *architecture* → draw it in ASCII here, don't route to the UI flow.)

### 7 · Self-review + gate
Scan \`design.md\`: placeholders, internal consistency, **every component has an interface + named dependencies**, ambiguity. Fix inline. Then ask the user to review before this feeds downstream.

### 8 · Handoff
"\`design.md\` written (+ N ADRs at \`status: proposed\`). Work decomposed into <k> components with their dependencies — ready for the task builder / harness." No tasks are written here.

---

## Guardrails

- **Stay in the HOW lane** - The WHAT is fixed. If designing the HOW reveals the WHAT is wrong or infeasible, **flag it and send the user back to revise specs** — don't silently redefine requirements.
- **Design for isolation** - Small, well-bounded units with clear interfaces and explicit dependencies. Both better design and the precondition for parallel task-building.
- **Don't implement, don't write tasks** - design.md + ADRs are the deliverables; code and tasks are downstream.
- **Don't auto-promote ADRs** - they ship at \`status: proposed\`.
- **Reference, don't duplicate** - point to ADRs and specs; don't re-argue or re-state them in design.md.
- **Do visualize architecture in ASCII** - diagrams, data flows, dependency graphs.
- **Do question assumptions** - including the user's and your own.`;

export function getOpsxDesignSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-design',
    description:
      'Enter design mode - a HOW-thinking partner that turns a settled WHAT (proposal + specs) into a technical design (design.md) and architecture decisions (ADRs), decomposing the work into well-bounded, parallelizable units. Use after requirements are settled, to think through how to build it.',
    instructions: DESIGN_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxDesignCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Design',
    description:
      'Enter design mode - turn a settled WHAT into a technical design (design.md) + ADRs, decomposed for parallel build',
    category: 'Workflow',
    tags: ['workflow', 'design', 'experimental', 'thinking'],
    content: `${DESIGN_BODY}

---

**Input**: The argument after \`/opsx:design\` is the change name to design (kebab-case), e.g. \`/opsx:design add-user-auth\`. If omitted, infer it from conversation context; if ambiguous, run \`openspec list --json\` and ask which change to design.`,
  };
}
