import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { runCLI } from '../helpers/run-cli.js';

describe('adr index command', () => {
  let tempDir: string;
  let adrDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-adr-cmd-'));
    adrDir = path.join(tempDir, 'docs', 'adr');
    await fs.mkdir(adrDir, { recursive: true });
  });
  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  const adr = (id: string, title: string, status = 'accepted') =>
    `---\nid: ${id}\ntitle: ${title}\nstatus: ${status}\ndate: 2026-05-17\n---\n# ${title}\n`;

  async function writeAdr(name: string, content: string) {
    await fs.writeFile(path.join(adrDir, name), content);
  }

  it('generates the registry README from ADR frontmatter', async () => {
    await writeAdr('ADR-0002-keys.md', adr('ADR-0002', 'bigserial keys'));
    await writeAdr('ADR-0009-auth.md', adr('ADR-0009', 'auth direction'));

    const result = await runCLI(['adr', 'index', '--dir', adrDir], { cwd: tempDir });
    expect(result.exitCode).toBe(0);

    const registry = await fs.readFile(path.join(adrDir, 'README.md'), 'utf-8');
    expect(registry).toContain('GENERATED by');
    expect(registry).toContain('| ID | Status | Title | Date | Change | Superseded by |');
    expect(registry).toContain('[ADR-0002](./ADR-0002-keys.md)');
    expect(registry).toContain('[ADR-0009](./ADR-0009-auth.md)');
    // numeric sort: 0002 before 0009
    expect(registry.indexOf('ADR-0002')).toBeLessThan(registry.indexOf('ADR-0009'));
  });

  it('--check passes when in sync and fails (exit 1) after drift', async () => {
    await writeAdr('ADR-0002-keys.md', adr('ADR-0002', 'bigserial keys'));
    await runCLI(['adr', 'index', '--dir', adrDir], { cwd: tempDir });

    const inSync = await runCLI(['adr', 'index', '--dir', adrDir, '--check'], { cwd: tempDir });
    expect(inSync.exitCode).toBe(0);
    expect(inSync.stdout).toContain('up to date');

    // add an ADR -> registry now stale
    await writeAdr('ADR-0003-new.md', adr('ADR-0003', 'new decision'));
    const drift = await runCLI(['adr', 'index', '--dir', adrDir, '--check'], { cwd: tempDir });
    expect(drift.exitCode).toBe(1);
    expect(drift.stdout).toContain('OUT OF SYNC');
  });

  it('refuses to overwrite a non-generated README without --force, then overwrites with it', async () => {
    await writeAdr('ADR-0002-keys.md', adr('ADR-0002', 'bigserial keys'));
    await fs.writeFile(path.join(adrDir, 'README.md'), '# Hand-written index\n\nDo not clobber me.\n');

    const refused = await runCLI(['adr', 'index', '--dir', adrDir], { cwd: tempDir });
    expect(refused.exitCode).toBe(1);
    expect(refused.stdout + refused.stderr).toMatch(/Refusing to overwrite/);
    // untouched
    expect(await fs.readFile(path.join(adrDir, 'README.md'), 'utf-8')).toContain('Hand-written index');

    const forced = await runCLI(['adr', 'index', '--dir', adrDir, '--force'], { cwd: tempDir });
    expect(forced.exitCode).toBe(0);
    expect(await fs.readFile(path.join(adrDir, 'README.md'), 'utf-8')).toContain('GENERATED by');
  });

  it('skips malformed ADRs, reports them, and still indexes the valid ones', async () => {
    await writeAdr('ADR-0002-keys.md', adr('ADR-0002', 'bigserial keys'));
    await writeAdr('ADR-0003-broken.md', '# no frontmatter\n');

    const result = await runCLI(['adr', 'index', '--dir', adrDir], { cwd: tempDir });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toMatch(/skipped due to parse errors/);
    expect(result.stdout).toContain('ADR-0003-broken.md');

    const registry = await fs.readFile(path.join(adrDir, 'README.md'), 'utf-8');
    expect(registry).toContain('[ADR-0002](./ADR-0002-keys.md)');
    expect(registry).not.toContain('ADR-0003');
  });

  it('emits JSON with --json', async () => {
    await writeAdr('ADR-0002-keys.md', adr('ADR-0002', 'bigserial keys'));
    const result = await runCLI(['adr', 'index', '--dir', adrDir, '--json'], { cwd: tempDir });
    expect(result.exitCode).toBe(0);
    const json = JSON.parse(result.stdout);
    expect(json.written).toBe(true);
    expect(json.count).toBe(1);
    expect(json.errors).toEqual([]);
  });

  it('errors (exit 1) when the ADR directory does not exist', async () => {
    const result = await runCLI(['adr', 'index', '--dir', path.join(tempDir, 'nope')], { cwd: tempDir });
    expect(result.exitCode).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/ADR directory/i);
  });
});
