import type { ParsedAdr } from './parse.js';

/**
 * Marker on the first line of a generated registry. Used to (a) detect a
 * generated file safe to overwrite vs a hand-written one, and (b) drive the
 * `--check` drift comparison.
 */
export const REGISTRY_MARKER =
  '<!-- GENERATED by `openspec adr index` — do not edit by hand. Run `openspec adr index` to refresh. -->';

/** Numeric sort key from an ADR id like "ADR-0037" -> 37 (non-numeric sort last). */
function adrSortKey(id: string): number {
  const match = id.match(/(\d+)/);
  return match ? Number(match[1]) : Number.POSITIVE_INFINITY;
}

/** A table cell: empties become "—"; pipes are escaped so they don't break the row. */
function cell(value: string | undefined): string {
  return value && value.trim() !== '' ? value.replace(/\|/g, '\\|') : '—';
}

/**
 * Renders the ADR registry: a single markdown table sorted by id, one row per
 * ADR, linking each id to its file. Pure and deterministic.
 */
export function renderRegistry(adrs: ParsedAdr[]): string {
  const sorted = [...adrs].sort((a, b) => {
    const ka = adrSortKey(a.id);
    const kb = adrSortKey(b.id);
    return ka !== kb ? ka - kb : a.id.localeCompare(b.id);
  });

  const lines = [
    REGISTRY_MARKER,
    '# ADR Registry',
    '',
    '| ID | Status | Title | Date | Change | Superseded by |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  for (const adr of sorted) {
    const idCell = `[${adr.id}](./${adr.filePath})`;
    lines.push(
      `| ${idCell} | ${cell(adr.status)} | ${cell(adr.title)} | ${cell(adr.date)} | ${cell(adr.change)} | ${cell(adr.supersededBy)} |`
    );
  }

  lines.push('');
  return lines.join('\n');
}
