/**
 * Reverse — idempotent capability spec scaffolder.
 *
 * Owns creation of the canonical `openspec/specs/<capability>/spec.md` skeleton so
 * the skill never hand-rolls the file shape. Idempotent on its own skeletons;
 * refuses to clobber human-authored content without `--force`.
 */
import path from 'node:path';
import { FileSystemUtils } from '../../utils/file-system.js';

/** Marks a spec as machine-generated and unreviewed. Also used to detect our own skeletons. */
export const DRAFT_BANNER =
  '<!-- DRAFT BASELINE — generated by `openspec reverse`. Review and ratify before relying on this spec. -->';

/** Capability dir-name rules: lowercase slug, matching existing `openspec/specs/` dirs. */
const CAPABILITY_SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export interface ScaffoldOptions {
  /** Purpose text; defaults to a `TBD` placeholder. */
  purpose?: string;
  /** Overwrite human-authored content. */
  force?: boolean;
}

export interface ScaffoldResult {
  /** Absolute path to the spec file. */
  specPath: string;
  /** True when a file was written (created or force-overwritten). */
  written: boolean;
  /** Why nothing was written, when `written` is false. */
  skipped?: 'existing-skeleton';
}

/**
 * Creates `<openspecDir>/specs/<capability>/spec.md`.
 *
 * - absent → create
 * - existing skeleton (ours, or empty) → idempotent no-op
 * - existing human content + no force → throws with remediation
 * - existing + force → overwrite
 */
export async function scaffoldCapabilitySpec(
  openspecDir: string,
  capability: string,
  options: ScaffoldOptions = {},
): Promise<ScaffoldResult> {
  if (!CAPABILITY_SLUG_RE.test(capability)) {
    throw new Error(
      `Invalid capability name '${capability}'. Use a lowercase slug (letters, digits, single hyphens), e.g. 'user-auth'.`,
    );
  }

  const specPath = FileSystemUtils.joinPath(openspecDir, 'specs', capability, 'spec.md');

  if (await FileSystemUtils.fileExists(specPath)) {
    const existing = await FileSystemUtils.readFile(specPath);
    if (!options.force && !isSkeleton(existing)) {
      throw new Error(
        `Refusing to overwrite existing spec at ${specPath}. It contains content not generated by 'openspec reverse'. Re-run with --force to overwrite, or edit it directly.`,
      );
    }
    if (!options.force && isSkeleton(existing)) {
      return { specPath, written: false, skipped: 'existing-skeleton' };
    }
  }

  await FileSystemUtils.createDirectory(path.dirname(specPath));
  await FileSystemUtils.writeFile(specPath, renderSkeleton(capability, options.purpose));
  return { specPath, written: true };
}

/** A skeleton is empty/whitespace, or carries our draft banner. */
function isSkeleton(content: string): boolean {
  return content.trim().length === 0 || content.includes(DRAFT_BANNER);
}

function renderSkeleton(capability: string, purpose?: string): string {
  return `${DRAFT_BANNER}

# ${capability} Specification

## Purpose
${purpose?.trim() || 'TBD: describe the capability this spec governs.'}

## Requirements
`;
}
